services:
  web:
    build: ./php
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: chatterbox

  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chatterbox
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
